const state = { flavor: 'sunny', tempo: 108, energy: 2, swing: 1, songName: 'Little Day Out', notes: [], vocalEnabled: false, vocalText: '', playing: false, context: null, timers: [] };

const presets = {
  sunny: { title: 'Sunny dock', tempo: 108, subtitle: 'bouncy bells · little handclaps', color: '#61b982' },
  rainy: { title: 'Rainy cabin', tempo: 84, subtitle: 'soft kalimba · window rain', color: '#6eb9c6' },
  seaside: { title: 'Saltwater stroll', tempo: 100, subtitle: 'breezy marimba · tide taps', color: '#4aaebf' },
  evening: { title: 'Lantern tide', tempo: 76, subtitle: 'warm music box · sleepy bass', color: '#8c81b5' },
};
const songSuitcases = {
  odoriko: { flavor: 'rainy', tempo: 96, energy: 2, label: 'Odoriko suitcase is packed: rainy sparkle, a close little band, and room for your MIDI.' },
  vampire: { flavor: 'evening', tempo: 132, energy: 3, label: 'vampire suitcase is packed: lantern drama, a bigger band, and room for your MIDI.' },
  'what-is-love': { flavor: 'sunny', tempo: 101, energy: 3, label: 'What Is Love? suitcase is packed: bright dock-pop, extra bounce, and room for your MIDI.' },
};
const defaultNotes = [72,74,76,79,76,74,72,69, 72,74,76,81,79,76,74,72, 69,72,74,76,74,72,69,67, 69,71,72,74,72,69,67,64]
  .map((pitch, index) => ({ pitch, start: index * .5, duration: index % 7 === 0 ? .85 : .42 }));
const instruments = [
  ['✦','Glockenspiel','the bright little lead'],
  ['⌁','Kalimba','soft chord sparkle'],
  ['◒','Upright bass','a warm walk home'],
  ['·','Hand percussion','tap tap, shuffle'],
  ['❋','Woodwind','a friendly answer'],
  ['◌','Marimba','round wooden sunshine'],
  ['⌇','Leafy guitar','little plucked chords'],
  ['≋','Brush shaker','a breezy edge'],
];

function setup() {
  state.notes = defaultNotes;
  makeWave(); renderTracks();
  document.querySelectorAll('.flavor').forEach(button => button.addEventListener('click', () => setFlavor(button.dataset.flavor)));
  document.querySelectorAll('.song-demo').forEach(button => button.addEventListener('click', () => loadSuitcase(button.dataset.demo)));
  document.querySelector('#midi-input').addEventListener('change', importMidi);
  document.querySelector('#demo-button').addEventListener('click', () => { state.notes = defaultNotes; state.songName = 'Little Day Out'; document.querySelector('#song-status').textContent = 'Cozy demo planted — a cheerful 16-bar melody is ready to arrange.'; refreshSong(); });
  document.querySelector('#energy').addEventListener('input', event => { state.energy = +event.target.value; document.querySelector('#energy-output').textContent = ['gentle', 'just right', 'full of beans'][state.energy - 1]; renderTracks(); });
  document.querySelector('#tempo').addEventListener('input', event => { state.tempo = +event.target.value; document.querySelector('#tempo-value').textContent = state.tempo; document.querySelector('#tempo-output').textContent = `${state.tempo} bpm`; });
  document.querySelector('#swing').addEventListener('input', event => { state.swing = +event.target.value; document.querySelector('#swing-output').textContent = ['straight', 'a little', 'extra bouncy'][state.swing]; });
  document.querySelector('#vocal-toggle').addEventListener('change', event => { state.vocalEnabled = event.target.checked; document.querySelector('#vocal-text').disabled = !state.vocalEnabled; });
  document.querySelector('#vocal-text').addEventListener('input', event => { state.vocalText = event.target.value; });
  document.querySelector('#play-button').addEventListener('click', togglePlay);
  document.querySelector('#download-button').addEventListener('click', downloadWav);
  document.querySelector('.share-button').addEventListener('click', () => { navigator.clipboard?.writeText(location.href); const button = document.querySelector('.share-button'); button.textContent = '✓ Link copied'; setTimeout(() => button.textContent = '↗ Share', 1500); });
}
function loadSuitcase(name) { const suitcase = songSuitcases[name]; setFlavor(suitcase.flavor); state.tempo = suitcase.tempo; state.energy = suitcase.energy; document.querySelector('#tempo').value = state.tempo; document.querySelector('#energy').value = state.energy; document.querySelector('#tempo-value').textContent = state.tempo; document.querySelector('#tempo-output').textContent = `${state.tempo} bpm`; document.querySelector('#energy-output').textContent = ['gentle', 'just right', 'full of beans'][state.energy - 1]; document.querySelector('#demo-note').textContent = suitcase.label; renderTracks(); }
function setFlavor(flavor) { state.flavor = flavor; const preset = presets[flavor]; state.tempo = preset.tempo; document.querySelector('#tempo').value = state.tempo; document.querySelector('#tempo-value').textContent = state.tempo; document.querySelector('#tempo-output').textContent = `${state.tempo} bpm`; document.querySelector('#arrangement-title').textContent = preset.title; document.querySelector('#listen-subtitle').textContent = `${preset.subtitle} · instrumental`; document.querySelectorAll('.flavor').forEach(b => { const chosen = b.dataset.flavor === flavor; b.classList.toggle('selected', chosen); b.setAttribute('aria-checked', chosen); }); makeWave(); renderTracks(); }
function refreshSong() { document.querySelector('#listen-title').textContent = state.songName; makeWave(); renderTracks(); }
function makeWave() { const root = document.querySelector('#waveform'); root.replaceChildren(); const seed = state.flavor.charCodeAt(0); for (let i=0;i<80;i++) { const bar = document.createElement('i'); const height = 8 + ((i * seed + i * i * 7) % 35); bar.style.height = `${height}px`; bar.style.background = presets[state.flavor].color; root.append(bar); } }
function renderTracks() { const root = document.querySelector('#tracks'); root.replaceChildren(); instruments.slice(0, state.energy * 2 + 2).forEach(([icon, name, detail], index) => { const row = document.createElement('div'); row.className = 'track'; row.innerHTML = `<span class="track-icon">${icon}</span><span>${name}<small>${detail}</small></span><span class="track-meter">${Array.from({length: 8}, (_, n) => `<i style="height:${5 + ((n * (index + 3) * 7) % 13)}px"></i>`).join('')}</span>`; root.append(row); }); }
function midiToHz(note) { return 440 * Math.pow(2, (note - 69) / 12); }
function noteSound(ctx, output, note, start, duration, type, gain) { const osc = ctx.createOscillator(); const amp = ctx.createGain(); osc.type = type; osc.frequency.value = midiToHz(note); amp.gain.setValueAtTime(.0001, start); amp.gain.exponentialRampToValueAtTime(gain, start + .02); amp.gain.exponentialRampToValueAtTime(.0001, start + duration); osc.connect(amp).connect(output); osc.start(start); osc.stop(start + duration + .03); }
function croakChat(ctx, output, note, start, duration, syllable) { const vowel = ({a:1.00,e:1.22,i:1.48,o:.83,u:.70}[syllable.toLowerCase().match(/[aeiou]/)?.[0]] || 1); const osc = ctx.createOscillator(), formant = ctx.createBiquadFilter(), amp = ctx.createGain(); osc.type = 'sawtooth'; osc.frequency.setValueAtTime(midiToHz(note) * .5, start); osc.frequency.exponentialRampToValueAtTime(midiToHz(note) * vowel, start + Math.min(.05, duration * .25)); formant.type='bandpass'; formant.Q.value=8; formant.frequency.value=900 + vowel * 520; amp.gain.setValueAtTime(.0001,start); amp.gain.exponentialRampToValueAtTime(.042,start+.016); amp.gain.exponentialRampToValueAtTime(.0001,start+Math.min(duration,.19)); osc.connect(formant).connect(amp).connect(output); osc.start(start); osc.stop(start+Math.min(duration,.2)+.02); }
function scheduleArrangement(ctx, destination, seconds=19) { const beat = 60 / state.tempo; const starts = state.notes.filter(n => n.start * beat < seconds); const tint = state.flavor === 'rainy' ? 'sine' : state.flavor === 'evening' ? 'triangle' : 'sine'; const syllables = (state.vocalText.match(/[a-zA-Z]+/g) || ['ba','da','mi','po','lu']); starts.forEach((n, i) => { const start = n.start * beat; noteSound(ctx, destination, n.pitch, start, Math.min(n.duration * beat, .5), tint, .13); if (state.vocalEnabled) croakChat(ctx, destination, n.pitch, start, Math.min(n.duration * beat, .26), syllables[i % syllables.length]); if (state.energy > 1 && i % 2 === 0) noteSound(ctx, destination, n.pitch - 12, start, .25, 'triangle', .035); if (state.energy > 1 && i % 4 === 0) noteSound(ctx, destination, n.pitch + (i % 8 ? 4 : 7), start + .13, .2, 'sine', .03); if (state.energy > 2 && i % 2 === 1) noteSound(ctx, destination, n.pitch - 5, start + .07, .16, 'triangle', .022); if (state.energy > 2 && i % 4 === 0) noteSound(ctx, destination, n.pitch - 12, start + .19, .1, 'sine', .025); }); for (let b=0;b<seconds/beat;b++) { const start=b*beat; const bass = [48,45,50,43][Math.floor(b/4)%4]; noteSound(ctx,destination,bass,start,.28,'triangle',.05); if(state.energy>1) noteSound(ctx,destination,84,start+(state.swing?beat*.5:beat*.45),.035,'square',.012); if(state.energy>2) { noteSound(ctx,destination,62+(b%3),start+.16,.08,'triangle',.018); noteSound(ctx,destination,96,start+(state.swing?beat*.72:beat*.65),.025,'square',.008); } } }
function togglePlay() { if (state.playing) return stopPlay(); state.context = new AudioContext(); const master = state.context.createGain(); master.gain.value = .65; master.connect(state.context.destination); scheduleArrangement(state.context, master); state.playing=true; document.querySelector('#play-button span').textContent='■'; document.querySelector('.playhead').animate([{left:'0%'},{left:'100%'}],{duration:19000,iterations:1}); state.timers.push(setTimeout(stopPlay, 19500)); }
function stopPlay() { state.timers.forEach(clearTimeout); state.timers=[]; state.context?.close(); state.context=null; state.playing=false; document.querySelector('#play-button span').textContent='▶'; }
function bufferToWav(buffer) { const channels=buffer.numberOfChannels, length=buffer.length*channels*2+44, view=new DataView(new ArrayBuffer(length)); const write=(o,s)=>[...s].forEach((c,i)=>view.setUint8(o+i,c.charCodeAt(0))); write(0,'RIFF');view.setUint32(4,36+buffer.length*channels*2,true);write(8,'WAVEfmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,channels,true);view.setUint32(24,buffer.sampleRate,true);view.setUint32(28,buffer.sampleRate*channels*2,true);view.setUint16(32,channels*2,true);view.setUint16(34,16,true);write(36,'data');view.setUint32(40,buffer.length*channels*2,true);let offset=44;for(let i=0;i<buffer.length;i++)for(let c=0;c<channels;c++){const s=Math.max(-1,Math.min(1,buffer.getChannelData(c)[i]));view.setInt16(offset,s<0?s*0x8000:s*0x7fff,true);offset+=2;}return new Blob([view],{type:'audio/wav'}); }
async function downloadWav() { const Offline = window.OfflineAudioContext || window.webkitOfflineAudioContext; if(!Offline) return; const offline=new OfflineAudioContext(2, 44100*19, 44100); const master=offline.createGain(); master.gain.value=.65; master.connect(offline.destination); scheduleArrangement(offline,master); const blob=bufferToWav(await offline.startRendering()); const link=Object.assign(document.createElement('a'),{href:URL.createObjectURL(blob),download:`${state.songName.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-croak-and-chord.wav`}); link.click(); URL.revokeObjectURL(link.href); }
function readVlq(data, pos) { let value=0, byte; do { byte=data[pos.i++]; value=(value<<7)|(byte&127); } while(byte&128); return value; }
function importMidi(event) { const file=event.target.files[0]; if(!file)return; const reader=new FileReader(); reader.onload=() => { try { const data=new Uint8Array(reader.result); const view=new DataView(data.buffer); if(String.fromCharCode(...data.slice(0,4))!=='MThd')throw Error('not MIDI'); const division=view.getUint16(12); let pos={i:14}, ticks=0, active=new Map(), notes=[]; while(pos.i<data.length){ if(String.fromCharCode(...data.slice(pos.i,pos.i+4))==='MTrk'){pos.i+=8;let running=0;while(pos.i<data.length&&String.fromCharCode(...data.slice(pos.i,pos.i+4))!=='MTrk'){ticks+=readVlq(data,pos);let status=data[pos.i];if(status&128){pos.i++;running=status}else status=running;if(status===0xff){const kind=data[pos.i++];const size=readVlq(data,pos);pos.i+=size;if(kind===47)break;continue;}const a=data[pos.i++], b=data[pos.i++];const key=`${status&15}-${a}`;if((status&0xf0)===0x90&&b){active.set(key,{pitch:a,tick:ticks});}else if((status&0xf0)===0x80||((status&0xf0)===0x90&&!b)){const onset=active.get(key);if(onset){notes.push({pitch:onset.pitch,start:onset.tick/division,duration:Math.max(.12,(ticks-onset.tick)/division)});active.delete(key);}}}}else pos.i++; } state.notes=notes.length?notes.sort((a,b)=>a.start-b.start).slice(0,128):defaultNotes; state.songName=file.name.replace(/\.(mid|midi)$/i,''); document.querySelector('#song-status').textContent=`${state.notes.length} little notes planted from “${file.name}”. Have a listen, then change the weather.`; refreshSong(); } catch(err){ document.querySelector('#song-status').textContent='That file did not look like a MIDI garden path — try a .mid or .midi file.'; } }; reader.readAsArrayBuffer(file); }
setup();
